version: "3.3"

services:
  app:
    image: ${IMAGE_NAME}
    ports:
      - "${PORT}:5000"
    volumes:
      - data:/data
    depends_on:
      - db
    expose:
      - "5000"
    environment:
      - "FLASK_APP=app.py"
      - "IMAGE_NAME=${IMAGE_NAME}"
      - "PROD_PORT=${PROD_PORT}"
      - "TEST_URL=${TEST_URL}"
  db:
    image: mysql:8.0
    ports:
      - "3306"
    volumes:
      - data:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      - "MYSQL_DATABASE=weightDB"
      - "MYSQL_USER=root"
      - "MYSQL_ROOT_PASSWORD=alpine"
    expose:
      - "3306"

volumes:
  data:
    


